#### Python Libraries For Data Science
- processing and analysing the data.There are nearly 20 python libraries for Data Science.Top five python libraries are
- 1. TensorFlow
- 2. Numpy
- 3. Scipy
- 4. Pandas
- 5. Matplotlib

#### Numpy
- Numerical Python is a base N-dimensional array package, is a python library.It is used to create multidimensional arrays for fast operations.

In [2]:
# Create 1D array
import numpy as np
array_1d = np.array([1,2,3,4,5])
print(array_1d)
print(type(array_1d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# Create 2D array
import numpy as np
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
d1 = [1,2,3,4,5,'s','a']
array_1d = np.array(d1)
print(array_1d)
print(type(array_1d))

['1' '2' '3' '4' '5' 's' 'a']
<class 'numpy.ndarray'>


In [6]:
import numpy as np
array_d = np.arange(15)
print(array_d)
#print(type(array_d))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
array_d = np.arange(10000)
print(array_d)

[   0    1    2 ... 9997 9998 9999]


In [9]:
import numpy as np
a1 = np.arange(10000).reshape(100,100)
print(a1)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [10]:
import numpy as np
ar1 = np.random.randint(0,2,size=(3,3,3,3))
print(ar1)

[[[[1 0 1]
   [1 1 0]
   [1 0 0]]

  [[0 1 1]
   [0 1 0]
   [1 0 0]]

  [[1 0 0]
   [1 0 1]
   [0 0 0]]]


 [[[0 1 0]
   [0 1 0]
   [0 1 0]]

  [[0 1 1]
   [1 1 0]
   [0 1 0]]

  [[1 1 0]
   [1 0 0]
   [0 1 1]]]


 [[[0 0 0]
   [0 1 1]
   [0 0 1]]

  [[1 1 0]
   [0 1 1]
   [0 0 0]]

  [[1 1 1]
   [0 1 1]
   [0 1 1]]]]


In [12]:
ar1[2][2][2][1]

1

In [13]:
print(ar1.shape)

(3, 3, 3, 3)


In [14]:
print(ar1.dtype)

int32


In [15]:
print(ar1.itemsize)

4


In [16]:
print(ar1.data)

In [20]:
import numpy as np
ar3 = np.arange(15).reshape(3,5)
print(ar3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
ls = [1,2,[4,5,6]]
ls[2][2]

6