In [5]:
import numpy as np
ar = np.arange(20).reshape(4,5)
print(ar)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [6]:
# reverse the array
ar[::-1]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [8]:
import numpy as np
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
x = [[1,2,3],[10,20,30],[11,22,33]]
y = np.array(x)
print(y)

[[ 1  2  3]
 [10 20 30]
 [11 22 33]]


In [10]:
z = y + 1
print(z)

[[ 2  3  4]
 [11 21 31]
 [12 23 34]]


In [11]:
p = z - 1
print(p)

[[ 1  2  3]
 [10 20 30]
 [11 22 33]]


In [12]:
s = z+p
print(s)

[[ 3  5  7]
 [21 41 61]
 [23 45 67]]


In [13]:
a = [1,2,3]
a1 = np.array(a)

In [16]:
print(a1)

[1 2 3]


In [17]:
print(np.sqrt(a1))

[1.         1.41421356 1.73205081]


In [19]:
print(np.sin(a1))

[0.84147098 0.90929743 0.14112001]


In [20]:
print(np.cos(a1))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [21]:
print(np.log(a1))

[0.         0.69314718 1.09861229]


### Pandas
- It was derived from PANEL Data, It is an open sourse python library.
- use cases
    - Data Cleaning
    - Data Transformation
    - Data Ananlysis
- Notations
    - Series
    - Data Frames

#####  Pandas Series

In [22]:
# Series
import pandas as pd
s = pd.Series([1,3,5])
print(s)

0    1
1    3
2    5
dtype: int64


In [23]:
# Series
import pandas as pd
s = pd.Series(['s','a','n','a'])
print(s)

0    s
1    a
2    n
3    a
dtype: object


In [24]:
import pandas as pd
ser = pd.Series([1,3,5])
print(ser)

0    1
1    3
2    5
dtype: int64


In [25]:
print(ser[1])

3


In [26]:
print(ser[2])

5


In [27]:
print(ser[1:])

1    3
2    5
dtype: int64


In [30]:
pd.Series([0,1,2],index=['a','b','c'])

a    0
b    1
c    2
dtype: int64

In [32]:
pd.Series([22,23,34],index=pd.date_range('22-12-2020','24-12-2020'))

2020-12-22    22
2020-12-23    23
2020-12-24    34
Freq: D, dtype: int64

In [37]:
import pandas as pd
import numpy as np
pd.Series(np.array(range(0,10))**2,index=range(1,11))

1      0
2      1
3      4
4      9
5     16
6     25
7     36
8     49
9     64
10    81
dtype: int32

In [36]:
pd.Series(np.array(range(0,10)))**2

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

In [35]:
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# Data Frames
# creating data frame by using list
import pandas as pd
data = [['sana',10],['sudha',20],['susha',30]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)

    Name  Age
0   sana   10
1  sudha   20
2  susha   30


In [39]:
df

Name  Age
0   sana   10
1  sudha   20
2  susha   30

In [40]:
# creating DataFrames by using Dictionaries
import pandas as pd
d1 = {'s1':10,'s2':20,'s3':30}
ser1 = pd.Series(d1)
print(ser1)

s1    10
s2    20
s3    30
dtype: int64


In [41]:
import pandas as pd
d2 = {'s1':11,'s2':22,'s3':33}
ser2 = pd.Series(d1)
print(ser2)

s1    10
s2    20
s3    30
dtype: int64


In [45]:
final = {'d1':d1,'d2':d2}
final = pd.DataFrame(final)
final

d1  d2
s1  10  11
s2  20  22
s3  30  33

In [43]:
final['d1']

s1    10
s2    20
s3    30
Name: d1, dtype: int64

In [44]:
final['d2']

s1    11
s2    22
s3    33
Name: d2, dtype: int64

In [47]:
df = pd.DataFrame({'name':['sana','sudha'],'age':[24,25],'profession':['engineer','doctor']})
df

name  age profession
0   sana   24   engineer
1  sudha   25     doctor